version: "3.8"
services:
  app:
    image: python_project:latest
    volumes:
    - ./:/app
    build: ./app/
    ports:
      - "8050:8050"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: postgres_project:latest
    build: ./db/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d database -U username"]
      interval: 5s
      timeout: 5s
      retries: 5 
